apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: return-api
  template:
    metadata:
      name: return-api
      namespace: return-api
      labels:
        name: return-api
    spec:
      containers:
        - name: return-api
          image: {{ .Values.image }}:{{ .Values.version }}
          livenessProbe:
            httpGet:
              port: {{ .Values.server.port }}
              path: {{ .Values.health.path }}