apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: return-api
  ports:
    - port: 80
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  type: NodePort