{{- range $app := .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  destination:
    namespace: null
    server: null
  source:
    path: /{{ $app }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
{{- end }}