apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: result-api
  template:
    metadata:
      name: result-api
      namespace: result-api
      labels:
        name: result-api
    spec:
      containers:
        - name: result-api
          image: {{ .Values.image }}:{{ .Values.version }}
          livenessProbe:
            httpGet:
              port: {{ .Values.server.port }}
              path: {{ .Values.health.path }}