apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: result-api
  ports:
    - port: 80
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  type: NodePort