spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ckrbqja/traffic-test-appofapps.git
    targetRevision: HEAD
    
applications:
  - traffic-delivery-fastapi
  - traffic-peak-spring
  - traffic-return-go

