spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ckrbqja/traffic-test-appofapps.git
    targetRevision: HEAD
    
applications:
  traffic-delivery-fastapi:
    destination:
      namespace: null
      server: null
#  traffic-peak-spring:
#    destination:
#      namespace: null
#      server: null

